version: '2'
services:
  server:
    image: nudj/server:local
    volumes:
      - ./ssl:/etc/ssl
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - web
      - hire
      - admin
    ports:
      - "80:80"
      - "443:443"
  web:
    image: nudj/web:local
    env_file: .env-web
    depends_on:
      - redis
      - api
  hire:
    image: nudj/hire:local
    env_file: .env-hire
    depends_on:
      - redis
      - api
  admin:
    image: nudj/admin:local
    env_file: .env-admin
    depends_on:
      - redis
      - api
  api:
    image: nudj/api:local
    env_file: .env-api
    depends_on:
      - db
    ports:
      - "81:81"
      - "82:82"
  redis:
    image: redis:alpine
    volumes:
      - ./sessionData:/data
  db:
    image: arangodb:3.1.17
    env_file: .env-db
    volumes:
      - ./dbdata:/var/lib/arangodb3
    ports:
      - "8529:8529"
