version: '2'
services:
  server:
    image: nudj/server:local
    volumes:
      - ./ssl:/etc/ssl
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - web
      - hire
      - admin
      - db
    ports:
      - "80:80"
      - "443:443"
  web:
    image: nudj/web-dev
    env_file: .env-web
    depends_on:
      - redis
      - api
    volumes:
      - ../../web/.zshrc:/root/.zshrc
      - ../../web/src/app:/usr/src/app
      - ../../web/src/test:/usr/src/test
      - ../../web/src/.npmrc:/usr/src/.npmrc
      - ../../web/src/nodemon.json:/usr/src/nodemon.json
      - ../../web/src/package.json:/usr/src/package.json
      - ../../web/src/webpack.config.js:/usr/src/webpack.config.js
      - ../../web/src/webpack.dll.js:/usr/src/webpack.dll.js
    command: /bin/zsh -c './node_modules/.bin/webpack --config ./webpack.dll.js --bail --hide-modules && ./node_modules/.bin/nodemon --config ./nodemon.json -e js,html,css --quiet --watch ./ --delay 250ms -x "printf \"\n\nBuilding...\n\" && ./node_modules/.bin/webpack --config ./webpack.config.js --bail --hide-modules && node ."'
  hire:
    image: nudj/hire-dev
    environment:
      - NPM_TOKEN
    env_file: .env-hire
    depends_on:
      - redis
      - api
    volumes:
      - ../../hire/.zshrc:/root/.zshrc
      - ../../hire/src/app:/usr/src/app
      - ../../hire/src/test:/usr/src/test
      - ../../hire/src/.flowconfig:/usr/src/.flowconfig
      - ../../hire/src/.npmrc:/usr/src/.npmrc
      - ../../hire/src/nodemon.json:/usr/src/nodemon.json
      - ../../hire/src/package.json:/usr/src/package.json
      - ../../hire/src/webpack.config.js:/usr/src/webpack.config.js
      - ../../hire/src/webpack.dll.js:/usr/src/webpack.dll.js
      - ../../hire/src/yarn.lock:/usr/src/yarn.lock
      - ../../hire/src/flow-typed:/usr/src/flow-typed
      - ../../framework/src:/usr/src/@nudj/framework
      - ../../api/src:/usr/src/@nudj/api
      - ../../library/src:/usr/src/@nudj/library
      - ../../components/src:/usr/src/@nudj/components
    command: /bin/zsh -c './node_modules/.bin/webpack --config ./webpack.dll.js --bail --hide-modules && ./node_modules/.bin/nodemon --config ./nodemon.json -e js,html,css --quiet --watch ./ --delay 250ms -x "printf \"\n\nBuilding...\n\" && ./node_modules/.bin/webpack --config ./webpack.config.js --bail --hide-modules && node ."'
  admin:
    image: nudj/admin-dev
    env_file: .env-admin
    depends_on:
      - redis
      - api
    volumes:
      - ../../admin/.zshrc:/root/.zshrc
      - ../../admin/src/app:/usr/src/app
      - ../../admin/src/test:/usr/src/test
      - ../../admin/src/.npmrc:/usr/src/.npmrc
      - ../../admin/src/nodemon.json:/usr/src/nodemon.json
      - ../../admin/src/package.json:/usr/src/package.json
      - ../../admin/src/webpack.config.js:/usr/src/webpack.config.js
      - ../../admin/src/webpack.dll.js:/usr/src/webpack.dll.js
    command: /bin/zsh -c './node_modules/.bin/webpack --config ./webpack.dll.js --bail --hide-modules && ./node_modules/.bin/nodemon --config ./nodemon.json -e js,html,css --quiet --watch ./ --delay 250ms -x "printf \"\n\nBuilding...\n\" && ./node_modules/.bin/webpack --config ./webpack.config.js --bail --hide-modules && node ."'
  api:
    image: nudj/api-dev
    env_file: .env-api
    depends_on:
      - db
    ports:
      - "81:81"
      - "82:82"
    volumes:
      - ../../api/.zshrc:/root/.zshrc
      - ../../api/src/gql:/usr/src/gql
      - ../../api/src/lib:/usr/src/lib
      - ../../api/src/mock:/usr/src/mock
      - ../../api/src/rest:/usr/src/rest
      - ../../api/src/test:/usr/src/test
      - ../../api/src/.npmignore:/usr/src/.npmignore
      - ../../api/src/.npmrc:/usr/src/.npmrc
      - ../../api/src/nodemon.json:/usr/src/nodemon.json
      - ../../api/src/package.json:/usr/src/package.json
      - ../../api/src/readme.md:/usr/src/readme.md
    command: /bin/sh -c './node_modules/.bin/nodemon --config ./nodemon.json -e js,html,css --quiet --watch ./ --delay 250ms -x "node ."'
  redis:
    image: redis:alpine
    volumes:
      - ./sessionData:/data
  db:
    image: arangodb:3.1.17
    env_file: .env-db
    volumes:
      - ./dbdata:/var/lib/arangodb3
      - ./dbdump:/dbdump
    ports:
      - "8529:8529"
