version: '2'
services:
  server:
    image: nginx:1.11.10-alpine
    volumes:
      - ./service.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - web
    ports:
      - "80:80"
    command: /bin/sh -c "nginx -g 'daemon off;'"
  web:
    image: nudj/web
    env_file: .env
