version: '2'
services:
  server:
    image: nudj/server:local
    volumes:
      - ../server/local/ssl:/etc/ssl
      - ../server/local/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "80:80"
      - "443:443"
  api:
    image: nudj/api-dev
    env_file: ../server/local/.env-api
    ports:
      - "81:81"
      - "82:82"
    volumes:
      - ../api/.zshrc:/root/.zshrc
      - ../api/src/gql:/usr/src/gql
      - ../api/src/gql-old:/usr/src/gql-old
      - ../api/src/lib:/usr/src/lib
      - ../api/src/mock:/usr/src/mock
      - ../api/src/rest:/usr/src/rest
      - ../api/src/test:/usr/src/test
      - ../api/src/.npmignore:/usr/src/.npmignore
      - ../api/src/.npmrc:/usr/src/.npmrc
      - ../api/src/nodemon.json:/usr/src/nodemon.json
      - ../api/src/package.json:/usr/src/package.json
      - ../api/src/index.js:/usr/src/index.js
    command: /bin/zsh -c './node_modules/.bin/nodemon --config ./nodemon.json -e js,html,css --quiet --watch ./ --delay 250ms -x "node ."'
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ../server/local/sessionData:/data
  db:
    image: arangodb:3.1.17
    env_file: ../server/local/.env-db
    volumes:
      - ../server/local/dbdata:/var/lib/arangodb3
      - ../server/local/dbdump:/dbdump
    ports:
      - "8529:8529"
  ui:
    image: nudj/test-ui
    shm_size: 1gb
    cap_add: ['SYS_ADMIN']
