version: '2'
services:
  server:
    image: nudj/server:development
    volumes:
      - ../server/local/ssl:/etc/ssl
      - ../server/local/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "80:80"
      - "443:443"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ../server/local/sessionData:/data
  db:
    image: arangodb:3.1.17
    env_file: ../server/local/.env-db
    volumes:
      - ../server/local/dbdata:/var/lib/arangodb3
    ports:
      - "8529:8529"
  ui:
    image: nudj/test-ui
    shm_size: 1gb
    cap_add: ['SYS_ADMIN']
