version: '2'
services:
  service:
    image: nudj/service:0.1.0
    volumes:
     - ./ssl:/etc/ssl
    depends_on:
     - web
    ports:
     - "80:80"
     - "443:443"
  web:
    image: nudj/web:0.2.0
