version: '2'
services:
  server:
    image: nudj/server:development
    restart: always
    volumes:
      - ../server/local/ssl:/etc/ssl
      - ../server/local/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "80:80"
      - "443:443"
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../server/local/sessionData:/data
  db:
    image: arangodb:3.1.17
    restart: always
    env_file: ../server/local/.env-db
    volumes:
      - ../server/local/dbdata:/var/lib/arangodb3
    ports:
      - "8529:8529"
  sql:
    image: mysql:5.7
    restart: always
    env_file: ../server/local/.env-sql
    volumes:
      - ../server/local/conf.d:/etc/mysql/conf.d
      - ../server/local/sqldata:/var/lib/mysql
    ports:
      - "3306:3306"
  ui:
    image: nudj/test-ui
    restart: always
    shm_size: 1gb
    cap_add: ['SYS_ADMIN']
