#!/bin/sh

environment=${1:-development}
version=${2:-$environment}
image="nudj/server:$version"
web="nudj/web:${3:-latest}"
webBeta="nudj/web:${4:-latest}"
hire="nudj/hire:${5:-latest}"
hireBeta="nudj/api:${6:-latest}"
api="nudj/api:${7:-latest}"
server="nudj$environment"
localPath="$environment"
remotePath="/home/nudjtech/$environment"
echo "Deploying $environment"

docker build -t $image $environment
docker push $image
rsync -rzP --delete --delete-excluded --exclude=Dockerfile --exclude=service.conf --exclude=.DS_Store --exclude=.dockerignore $localPath/ $server:$remotePath
ssh -t $server bash -c "'
cd $environment
sudo docker ps
sudo docker pull $image
sudo docker pull $web
sudo docker pull $webBeta
sudo docker pull $hire
sudo docker pull $hireBeta
sudo docker pull $api
sudo docker-compose up -d --force-recreate
sudo docker ps
'"
