version: '2'
services:
  server:
    image: nudj/server:1.0.0
    volumes:
      - ./ssl:/etc/ssl
    depends_on:
     - web
     - db
    ports:
     - "80:80"
     - "443:443"
  web:
    image: nudj/web:1.1.3
    env_file: .env-web
    depends_on:
      - redis
      - api
  redis:
    image: redis:alpine
    volumes:
      - ../sessionData:/data
  api:
    image: nudj/api:1.0.0
    env_file: .env-api
    depends_on:
      - db
  db:
    image: arangodb
    env_file: .env-db
    volumes:
      - ../dbdata:/var/lib/arangodb3
