version: '2'
services:
  server:
    image: nudj/server:1.0.0-beta
    volumes:
      - ./ssl:/etc/ssl
    depends_on:
     - web
    ports:
     - "80:80"
  web:
    image: nudj/web:1.0.0-beta
    env_file: .env
    depends_on:
      - api
  api:
    image: nudj/api:1.0.0-beta
    depends_on:
      - db
    ports:
      - "81:81"
  db:
    image: arangodb
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./dbdata:/var/lib/arangodb3
    ports:
      - "8529:8529"
    command: arangod --server.authentication false
volumes:
  dbdata:
