version: '2'
services:
  server:
    image: nudj/server:1.2.0
    volumes:
      - ./ssl:/etc/ssl
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
     - web
     - hire
     - db
    ports:
     - "80:80"
     - "443:443"
  web:
    image: nudj/web:1.3.4
    env_file: .env-web
    depends_on:
      - redis
      - api
  hire:
    image: nudj/hire:1.1.1
    env_file: .env-hire
    depends_on:
      - redis
      - api
  api:
    image: nudj/api:1.1.0
    env_file: .env-api
    depends_on:
      - db
  redis:
    image: redis:alpine
    volumes:
      - ../sessionData:/data
  db:
    image: arangodb
    env_file: .env-db
    volumes:
      - ../dbdata:/var/lib/arangodb3
      - ../dbdump:/dbdump
    command: arangod --log.level requests=trace --log.level info
