version: '2'
services:
  server:
    image: nudj/server:2.1.0
    volumes:
      - ./ssl:/etc/ssl
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - web
      - web-beta
      - hire
      - hire-beta
      - admin
    ports:
      - "80:80"
      - "443:443"
  web-beta:
    image: nudj/maintenance:latest
  web:
    image: nudj/web:5.1.0
    env_file: .env-web
    depends_on:
      - redis
      - api
  hire-beta:
    image: nudj/maintenance:latest
  hire:
    image: nudj/hire:3.0.0
    env_file: .env-hire
    depends_on:
      - redis
      - api
  admin:
    image: nudj/admin:4.1.0
    env_file: .env-admin
    depends_on:
      - redis
      - api
  api:
    image: nudj/api:3.3.0
    env_file: .env-api
    depends_on:
      - db
  redis:
    image: redis:alpine
    volumes:
      - ../sessionData:/data
  db:
    image: arangodb
    env_file: .env-db
    volumes:
      - ../dbdata:/var/lib/arangodb3
      - ../dbdump:/dbdump
