#!/bin/sh

environment=${1:-development}
server="nudj$environment"
dumpDir="dbdump"
localPath="/Users/nick/dev/nudj/server/local/$dumpDir"
echo "Dumping $environment"
cd $environment
bash -c "docker-compose exec db /bin/sh -c \"arangodump --overwrite true --output-directory \"/dbdump\" --server.database \"nudj\" --server.username \"$DB_USER\" --server.password \"$DB_PASS\"\""

echo "\nBackup for $environment completed to $localPath"
