#!/bin/sh

environment=${1:-development}
server="nudj$environment"
dumpDir="dbdump"
localPath="/keybase/private/nickcollings/backups/$environment/$(date '+%F')"
remotePath="/home/nudjtech/$dumpDir"
echo "Dumping $environment"
command='docker-compose exec db /bin/sh -c \"arangodump --overwrite true --output-directory "/dbdump" --server.database "nudj" --server.username "\$DB_USER" --server.password "\$DB_PASS"\"'

ssh -t $server bash -c "'
cd $environment
ls -la
echo '======'
sudo env \$(cat .env-api | xargs) bash -c \"$command\"
echo '======'
'"
mkdir -p $localPath
rsync -avz --delete -e "ssh" --rsync-path="sudo rsync" $server:$remotePath/ $localPath
echo "\nBackup for $environment completed to $localPath"
