#!/bin/sh

environment=$1
if [ -z "$1" ]
then
  echo "Must supply an environment - e.g. ENV=development INPUT_DIR=/Users/nick/dev/nudj/backups/development/2018-01-29"
  exit 1
fi

migration=$2
if [ -z "$2" ]
then
  echo "Must supply a migration name - e.g. MIGRATION=00000-init"
  exit 1
fi

direction=${3:-up}
server="nudj$environment"
dbmigrations="dbmigrations"

echo "Restoring $environment"

if [[ "$environment" = "development" || "$environment" = "staging" || "$environment" = "production" ]]; then
  remotePath="/home/nudjtech/$dbmigrations"
  rsync -avz --delete -e "ssh" --rsync-path="sudo rsync" $PWD/migrations/ $server:$remotePath

  command="docker-compose run --rm -v $remotePath:/$dbmigrations api /bin/sh -c \"node /$dbmigrations $migration $DB_USER $DB_PASS\" && rm -rf $remotePath"

  ssh -t $server bash -c "'
  cd $environment
  echo '======'
  sudo $command
  echo '======'
  '"
else
  bash -c "docker-compose -f ./local/docker-compose-dev.yml run --rm -v $PWD/migrations:/usr/src/dbmigrations api /bin/sh -c \"node ./dbmigrations $migration $direction $DB_USER $DB_PASS\""
fi

echo "\nApplication of $migration in direction $direction onto $environment complete"
