#!/bin/sh

environment=${1:-development}
version=${2:-$environment}
image="nudj/server:$version"
web="nudj/web:${3:-latest}"
hire="nudj/hire:${4:-latest}"
admin="nudj/admin:${5:-latest}"
api="nudj/api:${6:-latest}"
maintenance="nudj/maintenance:latest"
server="nudj$environment"
localPath="$environment"
remotePath="/home/nudjtech/$environment"
echo "Deploying $environment"

# docker build -t $image $environment
# docker push $image
rsync -avz --delete --delete-excluded --exclude=Dockerfile --exclude=service.conf --exclude=.DS_Store --exclude=.dockerignore --exclude=dbdump $localPath/ $server:$remotePath
ssh -t $server bash -c "'
cd $environment
sudo docker ps
echo ''
sudo docker pull $image
echo ''
sudo docker pull $web
echo ''
sudo docker pull $hire
echo ''
sudo docker pull $admin
echo ''
sudo docker pull $api
echo ''
sudo docker pull $maintenance
echo ''
sudo docker-compose up -d --remove-orphans
echo ''
sudo docker ps
'"
