#!/bin/sh

validEnvironment() {
  [ "$1" = "development" ] || \
  [ "$1" = "staging" ] || \
  [ "$1" = "production" ]
}

environment=$1
if [ -z "$1" ]
then
  echo "Must supply an environment - e.g. ENV=development"
  exit 1
fi

if ! validEnvironment $environment
then
  echo "Must supply a valid environment - e.g. ENV=development"
  exit 1
fi

if [[ "$environment" = "production" ]]; then
  if [ -z "$2" ]; then
    echo "Must supply a server version - e.g. SERVER=1.0.0"
    exit 1
  fi
  if [ -z "$3" ]; then
    echo "Must supply a web version - e.g. WEB=1.0.0"
    exit 1
  fi
  if [ -z "$4" ]; then
    echo "Must supply a hire version - e.g. HIRE=1.0.0"
    exit 1
  fi
  if [ -z "$5" ]; then
    echo "Must supply a admin version - e.g. ADMIN=1.0.0"
    exit 1
  fi
  if [ -z "$6" ]; then
    echo "Must supply a api version - e.g. API=1.0.0"
    exit 1
  fi
fi

image="nudj/server:${2}"
web="nudj/web:${3:-latest}"
hire="nudj/hire:${4:-latest}"
admin="nudj/admin:${5:-latest}"
api="nudj/api:${6:-latest}"
maintenance="nudj/maintenance:latest"
server="nudj$environment"
localPath="$environment"
remotePath="/home/nudjtech/$environment"

echo "Deploying $environment"

rsync -avz --delete --delete-excluded --exclude=Dockerfile --exclude=service.conf --exclude=.DS_Store --exclude=.dockerignore --exclude=dbdump $localPath/ $server:$remotePath
ssh -t $server bash -c "'
cd $environment
sudo docker ps
echo ''
sudo docker pull $image
echo ''
sudo docker pull $web
echo ''
sudo docker pull $hire
echo ''
sudo docker pull $admin
echo ''
sudo docker pull $api
echo ''
sudo docker pull $maintenance
echo ''
sudo docker-compose up -d --remove-orphans --force-recreate
echo ''
sudo docker ps
'"
