#!/bin/sh

inputDir=$1
if [ -z "$1" ]
then
  echo "Must supply an absolute path to the input directory - e.g. make restoreLocal INPUT_DIR=/Users/nick/dev/nudj/server/local/dbdump"
  exit 1
fi

echo "Restoring local from $inputDir"
cd local
bash -c "docker-compose run --rm -v $inputDir:/dbrestore db /bin/sh -c \"arangorestore --input-directory \"/dbrestore\" --server.endpoint http+tcp://db:8529 --server.database \"nudj\" --server.username \"$DB_USER\" --server.password \"$DB_PASS\"\""

echo "\nRestore of local from $inputDir completed"
