version: '2'
services:
  server:
    image: nudj/server:demo
    restart: always
    volumes:
      - ./ssl:/etc/ssl
      - ./.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "80:80"
      - "443:443"
  web:
    image: nudj/web:latest
    restart: always
    env_file: .env-web
  hire:
    image: nudj/hire:latest
    restart: always
    env_file: .env-hire
  admin:
    image: nudj/admin:latest
    restart: always
    env_file: .env-admin
  api:
    image: nudj/api:latest
    restart: always
    env_file: .env-api
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ../sessionData:/data
  db:
    image: arangodb
    restart: always
    env_file: .env-db
    volumes:
      - ../dbdata:/var/lib/arangodb3
