#!/bin/sh

environment=$1
script=$2
dockerRun=$3
scriptsDir=$4
arg=$5

cd $environment

echo "$environment: Executing script on api service\n"
$dockerRun -v $scriptsDir:/usr/src/scripts api /bin/sh -c "node /usr/src/scripts $script $arg"
