#!/bin/sh

environment=$1
dockerRun=${2:-'docker-compose run --rm'}
devopsDir=${3:-'/home/nudjtech/devops'}
inputDir=${4:-'/home/nudjtech/dbrestore'}

cd $environment

echo "$environment: Dropping existing collections"
$dockerRun -v $devopsDir/api:/usr/src/devops api node /usr/src/devops/drop-collections

echo "$environment: Fetching db connection variables from envkey"
dbEnvVars=$($dockerRun -v $devopsDir/api:/usr/src/devops api node /usr/src/devops/extract-envkeys DB_HOST DB_PORT DB_NAME DB_USER DB_PASS)

echo "$environment: Executing restore script on db service"
$dockerRun -v $devopsDir/db:/devops -v $inputDir:/dbrestore $dbEnvVars db /devops/restore
